spring.application.name=service-desk-system
server.port = 8081

#Database Configuration
spring.datasource.url = jdbc:postgresql://localhost:5434/service_desk
spring.datasource.username = postgres
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql= true